name: Auto Scrape Numbers3

on:
  schedule:
    - cron: '0 11 * * 1-5'  # JST 20:00（UTC 11:00）、月〜金
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies and headless Chrome
        run: |
          sudo apt update
          sudo apt install -y wget unzip xvfb \
            libglib2.0-0 libnss3 libxi6 libxcomposite1 libxss1 \
            libatk-bridge2.0-0 libgtk-3-0 libasound2t64

          # Install Chrome 138
          wget https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.92/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/chrome
          sudo ln -sf /opt/chrome/chrome /usr/bin/google-chrome

          # Install ChromeDriver 138
          wget https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.92/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install Python packages
        run: pip install selenium pandas

      - name: Run scraping script
        run: xvfb-run -a python scrapingnumbers3.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add numbers3.csv
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto update numbers3.csv [skip ci]"
            git push
          fi
