name: Auto Scrape Numbers3

on:
  schedule:
    - cron: '0 11 * * 1-5'  # JST 20:00（UTC 11:00）、月〜金
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: 'matching'

      - name: Install Python dependencies
        run: |
          pip install selenium pandas

      - name: Run scraping script
        run: |
          python scrapingnumbers3.py
