name: Auto Scrape Numbers3

on:
  schedule:
    - cron: '0 11 * * 1-5'  # JST 20:00 → UTC 11:00（月〜金）
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: windows-latest  # ⬅️ chromedriver.exeを使うには必須

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Google Chrome
        run: |
          choco install googlechrome -y

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium pandas

      - name: Run scraper
        run: python scrapingnumbers3.py
