- name: Install ChromeDriver
  run: |
    echo "[INFO] Getting Chrome version..."
    if command -v google-chrome > /dev/null; then
      CHROME_BIN=$(command -v google-chrome)
    elif [ -f /usr/bin/google-chrome ]; then
      CHROME_BIN="/usr/bin/google-chrome"
    else
      echo "[ERROR] google-chrome not found"
      exit 1
    fi

    CHROME_VERSION=$($CHROME_BIN --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
    echo "Detected Chrome major version: $CHROME_VERSION"

    DRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
    echo "Downloading ChromeDriver version: $DRIVER_VERSION"

    wget https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
    unzip chromedriver_linux64.zip
    sudo mv chromedriver /usr/local/bin/
    sudo chmod +x /usr/local/bin/chromedriver
